module.exports =
  commit_comment: require './commit-comment'
  create: require './create'
  delete: require './delete'
  deployment: require './deployment'
  issue_comment: require './issue-comment'
  issues: require './issues'
  ping: require './ping'
  pull_request: require './pull-request'
  pull_request_review_comment: require './pull-request-review-comment'
  push: require './push'
  unhandled: require './unhandled'
  watch: require './watch'
